version: '3.8'

services:
  # Hotel Room Microservice
  api:
    build: .
    ports:
      - "3001:3001"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/hotel_db
      - PORT=3001
    depends_on:
      - mongodb
    networks:
      - hotel-network
    restart: unless-stopped

  # MongoDB Service
  mongodb:
    image: mongo:latest
    ports:
      - "27020:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - hotel-network
    restart: unless-stopped

networks:
  hotel-network:
    driver: bridge

volumes:
  mongodb_data: 